server:
  port: 9527
  servlet:
    session:
      timeout: 120m




spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1 from dual
        pool-name: HismartHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: root#123456!
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.50.143:3306/sink?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          #数据源-2，名称为 test
        PosgreSQL:
          username: hs_01
          password: Hismart@2019
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.73.13:25108/edw?currentSchema=ods
  aop:
    proxy-target-class: true

  kafka:
    bootstrap-servers: 192.168.73.11:21005,192.168.73.12:21005
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: consumer-contorller
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.hismart.ogg.elk.sink.modules.center.entity
  mapper-locations: classpath*:com/hismart/ogg/elk/sink/**/mapping/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


hismart:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /system/sink_user/api/v1/login,/system/sink_user/api/v1/loginResponse,/system/sink_user/api/v1/logoutNotice
    # token有效期，单位秒
    jwtTimeOut: 3600
  rerun:
    number: 5
  key: jahsdahgkdagkasdahjakdajsldja





logging:
  level:
    root: info

thread:
  poll:
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 100
    keepAliveSeconds: 10

#闲时间周期。超过这个时长没有访问的数据库连接将被释放。默认为10分钟
cleanup:
  data:
    sources:
      job:
        cronExpression: 0 */2 * * * ?
    ip: 192.168.50.143


# 定时检查ogg脚本健康状态
check:
  cron: 0 */2 * * * ?




